// <auto-generated />
using System;
using ApprovalFlow.ConfigPolicy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApprovalFlow.ConfigPolicy.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ConfigPolicyDbContext))]
    partial class ConfigPolicyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("config_policy")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApprovalFlow.ConfigPolicy.Domain.Entities.FxRateEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("PolicyDocumentId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RateToBaseCurrency")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("PolicyDocumentId");

                    b.ToTable("FxRates", "config_policy");
                });

            modelBuilder.Entity("ApprovalFlow.ConfigPolicy.Domain.Entities.KnownVendorEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PolicyDocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("PolicyDocumentId");

                    b.ToTable("KnownVendors", "config_policy");
                });

            modelBuilder.Entity("ApprovalFlow.ConfigPolicy.Domain.Entities.PolicyDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AutonomyCeilingUsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<double>("AutonomyMinConfidence")
                        .HasColumnType("double precision");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Markdown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_PolicyDocuments_Active")
                        .HasFilter("\"IsActive\" = true");

                    b.ToTable("PolicyDocuments", "config_policy");
                });

            modelBuilder.Entity("ApprovalFlow.ConfigPolicy.Domain.Entities.FxRateEntry", b =>
                {
                    b.HasOne("ApprovalFlow.ConfigPolicy.Domain.Entities.PolicyDocument", null)
                        .WithMany("FxRates")
                        .HasForeignKey("PolicyDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApprovalFlow.ConfigPolicy.Domain.Entities.KnownVendorEntry", b =>
                {
                    b.HasOne("ApprovalFlow.ConfigPolicy.Domain.Entities.PolicyDocument", null)
                        .WithMany("KnownVendors")
                        .HasForeignKey("PolicyDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApprovalFlow.ConfigPolicy.Domain.Entities.PolicyDocument", b =>
                {
                    b.Navigation("FxRates");

                    b.Navigation("KnownVendors");
                });
#pragma warning restore 612, 618
        }
    }
}
